name: gran_turismo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: 0.1.3
  json_annotation: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 3.4.1
  build_runner: 1.10.2

flutter:
  uses-material-design: true
  
  assets:
    - car_list.json